# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, ci ]
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      # Runs a set of commands using the runners shell
      - name: build boost
        run:  python3 build.py --setup --boost --par=4

      - name: build relic
        run:  python3 build.py --setup --relic --par=4
          
      - name: build libOTe
        run:  python3 build.py --par=4 -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON 

      - name: unit tests
        run:  ./out/build/linux/frontend/frontend_libOTe -u
       

      - name: find source tree
        run: |
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=../../
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            
      - name: hint test
        run: |
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -D LIBOTE_HINT=../..
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

      - name: install prefix test
        run: |
            python3 build.py --setup -boost --relic --install=~/install
            python3 build.py --install=~/install
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/install
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            

      - name: install test
        run: |
            python3 build.py --setup -boost --relic --install --sudo
            python3 build.py --install --sudo
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: ilammy/msvc-dev-cmd@v1

      # Runs a set of commands using the runners shell
      - name: build boost
        run: python3 build.py --setup --boost --par=4

      - name: build relic
        run: python3 build.py --setup --relic --par=4
        
      - name: build libOTe
        run:  python3 build.py --par=4 -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON  -G Ninja

        
      - name: unit test
        run:  ./out/build/x64-Release/frontend/frontend_libOTe.exe -u
          
      - name: find source tree
        run: |
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=../../
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -rf out/
            cd ../..
            
      - name: hint test
        run: |
            python3 build.py --setup 
            python3 build.py
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -D LIBOTE_HINT=../..
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -rf out/
            cd ../..

      - name: install prefix test
        run: |
            python3 build.py --setup --install=~/install 
            python3 build.py --install=~/install 
            cd libOTe_Tests/cmakeTests
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/install
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -rf out/
            cd ../..
  #build-macOS:
  #  # The type of runner that the job will run on
  #  runs-on: macos-11.0
  #
  #  # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
  #    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v2
  #      with:
  #          submodules: recursive
  #
  #    # Runs a set of commands using the runners shell
  #    - name: build test
  #      run: |
  #        python3 build.py --setup --relic --boost
  #        python3 build.py --noPar -- -D ENABLE_ALL_OT=ON -D ENABLE_RELIC=ON 
  #        ./out/build/linux/frontend/frontend_libOTe -u
  #